"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { supabase, type CaseStudy } from "@/lib/supabase";
import { FileDown, Copy, ExternalLink } from "lucide-react";

interface FormData {
  clientType: string;
  challenge: string;
  solution: string;
  result: string;
  tone: string;
  industry: string;
  clientQuote: string;
}

const toneOptions = [
  "Professional",
  "Friendly",
  "Bold",
  "Casual",
  "Persuasive",
];

const industryOptions = [
  "SaaS",
  "Ecommerce",
  "Coaching",
  "Agency",
  "Local Business",
];

export default function Page() {
  const [formData, setFormData] = useState<FormData>({
    clientType: "",
    challenge: "",
    solution: "",
    result: "",
    tone: "",
    industry: "",
    clientQuote: "",
  });

  const [generatedCaseStudy, setGeneratedCaseStudy] = useState<string>("");
  const [socialMediaText, setSocialMediaText] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [previousCaseStudies, setPreviousCaseStudies] = useState<CaseStudy[]>(
    [],
  );
  const [isLoadingPrevious, setIsLoadingPrevious] = useState(true);

  const handleInputChange = (field: keyof FormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const fetchPreviousCaseStudies = async () => {
    try {
      const { data, error } = await supabase
        .from("case_studies")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(10);

      if (error) {
        console.error("Error fetching case studies:", error);
        return;
      }

      setPreviousCaseStudies(data || []);
    } catch (error) {
      console.error("Error fetching case studies:", error);
    } finally {
      setIsLoadingPrevious(false);
    }
  };

  useEffect(() => {
    fetchPreviousCaseStudies();
  }, []);

  const generateCaseStudy = async () => {
    setIsGenerating(true);

    try {
      const response = await fetch("/api/generate-case-study", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error("Failed to generate case study");
      }

      const data = await response.json();
      setGeneratedCaseStudy(data.caseStudy);
      setSocialMediaText(data.socialMediaText || "");

      // Refresh the previous case studies list
      if (data.saved) {
        fetchPreviousCaseStudies();
      }
    } catch (error) {
      console.error("Error generating case study:", error);
      setGeneratedCaseStudy(
        "Sorry, there was an error generating your case study. Please try again.",
      );
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    generateCaseStudy();
  };

  const isFormValid =
    formData.clientType &&
    formData.challenge &&
    formData.solution &&
    formData.result &&
    formData.tone &&
    formData.industry;

  const exportToPDF = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    // Set up the document
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let yPosition = margin;

    // Helper function to add text with word wrapping
    const addWrappedText = (
      text: string,
      fontSize: number,
      isBold: boolean = false,
    ) => {
      doc.setFontSize(fontSize);
      if (isBold) {
        doc.setFont(undefined, "bold");
      } else {
        doc.setFont(undefined, "normal");
      }

      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, margin, yPosition);
      yPosition += lines.length * (fontSize * 0.4) + 10;
    };

    // Extract headline from generated case study
    const lines = generatedCaseStudy.split("\n");
    const headline = lines[0] || "Case Study";
    const content = lines.slice(1).join("\n");

    // Add headline
    addWrappedText(headline, 18, true);
    yPosition += 10;

    // Add main content
    addWrappedText(content, 12);

    // Add client quote if provided
    if (formData.clientQuote) {
      yPosition += 10;
      addWrappedText(`"${formData.clientQuote}"`, 12, true);
    }

    // Add footer
    yPosition += 20;
    doc.setFontSize(10);
    doc.setFont(undefined, "italic");
    doc.text("Generated by Instant Case Study", margin, yPosition);

    // Save the PDF
    const fileName = `case-study-${formData.clientType.replace(/\s+/g, "-").toLowerCase()}.pdf`;
    doc.save(fileName);
  };

  const [copySuccess, setCopySuccess] = useState<boolean>(false);

  const copyToClipboard = async () => {
    try {
      // Replace placeholder URL with actual URL
      const finalText = socialMediaText.replace(
        "https://your-app-url.com",
        window.location.origin,
      );
      await navigator.clipboard.writeText(finalText);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  const openSocialLink = (platform: string) => {
    const baseUrl = window.location.origin;
    const urls = {
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(baseUrl)}`,
      twitter: `https://twitter.com/intent/tweet?url=${encodeURIComponent(baseUrl)}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(baseUrl)}`,
      reddit: `https://www.reddit.com/submit?url=${encodeURIComponent(baseUrl)}`,
    };

    window.open(urls[platform as keyof typeof urls], "_blank");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            Instant Case Study
          </h1>
          <p className="text-lg text-gray-600">
            Transform your project wins into compelling case studies in minutes
          </p>
        </div>

        {/* Form */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Project Details</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="clientType">Client Type</Label>
                  <Input
                    id="clientType"
                    placeholder="e.g., Tech Startup, Local Restaurant, E-commerce Brand"
                    value={formData.clientType}
                    onChange={(e) =>
                      handleInputChange("clientType", e.target.value)
                    }
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="tone">Tone</Label>
                  <Select
                    value={formData.tone}
                    onValueChange={(value) => handleInputChange("tone", value)}
                    required
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select tone" />
                    </SelectTrigger>
                    <SelectContent>
                      {toneOptions.map((tone) => (
                        <SelectItem key={tone} value={tone}>
                          {tone}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="industry">Industry</Label>
                <Select
                  value={formData.industry}
                  onValueChange={(value) =>
                    handleInputChange("industry", value)
                  }
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select industry" />
                  </SelectTrigger>
                  <SelectContent>
                    {industryOptions.map((industry) => (
                      <SelectItem key={industry} value={industry}>
                        {industry}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="challenge">Challenge</Label>
                <Textarea
                  id="challenge"
                  placeholder="Describe the main challenge or problem your client was facing..."
                  value={formData.challenge}
                  onChange={(e) =>
                    handleInputChange("challenge", e.target.value)
                  }
                  rows={4}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="solution">Solution</Label>
                <Textarea
                  id="solution"
                  placeholder="Explain the solution you provided and how you implemented it..."
                  value={formData.solution}
                  onChange={(e) =>
                    handleInputChange("solution", e.target.value)
                  }
                  rows={4}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="result">Result</Label>
                <Textarea
                  id="result"
                  placeholder="Share the specific results, metrics, and outcomes achieved..."
                  value={formData.result}
                  onChange={(e) => handleInputChange("result", e.target.value)}
                  rows={4}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="clientQuote">Client Quote (Optional)</Label>
                <Textarea
                  id="clientQuote"
                  placeholder="Include a testimonial or quote from your client..."
                  value={formData.clientQuote}
                  onChange={(e) =>
                    handleInputChange("clientQuote", e.target.value)
                  }
                  rows={3}
                />
              </div>

              <Button
                type="submit"
                className="w-full"
                size="lg"
                disabled={!isFormValid || isGenerating}
              >
                {isGenerating
                  ? "Generating Your Case Study..."
                  : "Generate My Case Study"}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Generated Case Study */}
        {generatedCaseStudy && (
          <Card className="mb-8">
            <CardHeader>
              <CardTitle>Your Generated Case Study</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="prose max-w-none">
                <div className="whitespace-pre-line text-gray-800 leading-relaxed mb-6">
                  {generatedCaseStudy}
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-6 pt-6 border-t">
                <div className="flex flex-col sm:flex-row gap-4">
                  <Button
                    onClick={exportToPDF}
                    variant="outline"
                    className="flex items-center gap-2"
                  >
                    <FileDown className="h-4 w-4" />
                    Export as PDF
                  </Button>
                </div>

                {/* Share on Socials Section */}
                {socialMediaText && (
                  <div className="space-y-4">
                    <h3 className="text-lg font-semibold text-gray-900">
                      Share on Socials
                    </h3>

                    <div className="space-y-3">
                      <Textarea
                        value={socialMediaText.replace(
                          "https://your-app-url.com",
                          window.location.origin,
                        )}
                        readOnly
                        rows={4}
                        className="resize-none bg-gray-50"
                        placeholder="Your social media post will appear here..."
                      />

                      <div className="flex flex-col sm:flex-row gap-3">
                        <Button
                          onClick={copyToClipboard}
                          variant="outline"
                          className="flex items-center gap-2"
                        >
                          <Copy className="h-4 w-4" />
                          {copySuccess ? "Copied!" : "📋 Copy to Clipboard"}
                        </Button>

                        <div className="flex gap-2">
                          <Button
                            onClick={() => openSocialLink("linkedin")}
                            size="sm"
                            className="bg-blue-600 hover:bg-blue-700 text-white px-3"
                          >
                            <svg
                              className="h-4 w-4"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                            >
                              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                            </svg>
                          </Button>

                          <Button
                            onClick={() => openSocialLink("twitter")}
                            size="sm"
                            className="bg-black hover:bg-gray-800 text-white px-3"
                          >
                            <svg
                              className="h-4 w-4"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                            >
                              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                            </svg>
                          </Button>

                          <Button
                            onClick={() => openSocialLink("facebook")}
                            size="sm"
                            className="bg-blue-500 hover:bg-blue-600 text-white px-3"
                          >
                            <svg
                              className="h-4 w-4"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                            >
                              <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                            </svg>
                          </Button>

                          <Button
                            onClick={() => openSocialLink("reddit")}
                            size="sm"
                            className="bg-orange-500 hover:bg-orange-600 text-white px-3"
                          >
                            <svg
                              className="h-4 w-4"
                              viewBox="0 0 24 24"
                              fill="currentColor"
                            >
                              <path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.25-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z" />
                            </svg>
                          </Button>
                        </div>
                      </div>

                      {copySuccess && (
                        <p className="text-sm text-green-600 font-medium">
                          Post text copied to clipboard. Paste it when prompted.
                        </p>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Previous Case Studies */}
        <Card>
          <CardHeader>
            <CardTitle>Previous Case Studies</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoadingPrevious ? (
              <div className="text-center py-8 text-gray-500">
                Loading previous case studies...
              </div>
            ) : previousCaseStudies.length === 0 ? (
              <div className="text-center py-8 text-gray-500">
                No case studies yet. Generate your first one above!
              </div>
            ) : (
              <div className="space-y-4">
                {previousCaseStudies.map((caseStudy) => {
                  const headline =
                    caseStudy.ai_output.split("\n")[0] || "Case Study";
                  const resultSnippet =
                    caseStudy.result.length > 100
                      ? caseStudy.result.substring(0, 100) + "..."
                      : caseStudy.result;
                  const date = new Date(
                    caseStudy.created_at,
                  ).toLocaleDateString();

                  return (
                    <div
                      key={caseStudy.id}
                      className="border rounded-lg p-4 hover:bg-gray-50 transition-colors"
                    >
                      <h3 className="font-semibold text-lg mb-2 text-gray-900">
                        {headline}
                      </h3>
                      <p className="text-gray-600 mb-2">{resultSnippet}</p>
                      <div className="flex justify-between items-center text-sm text-gray-500">
                        <span>
                          {caseStudy.client_type} • {caseStudy.industry}
                        </span>
                        <span>{date}</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
